function layerData = textStringData()
    % Handles to the functions in this folder
    fcnPrep = @textStringPrep;
    fcnDraw = @textStringDraw;

    settingNames = {'Size', 'Xpos', 'Ypos'};
    % Data corresponds to the above setting names
    settingDefaults = [50; 220; 240];
    % Defaults for timing
    timingData = [60; 0; 0; 0];
    % Needed for layer settings manager to work
    settings.global = 1;
    settings.edit{1}  = {'Text String', 'FlyFly'};

    layerData = struct(...
    'name',       'Text String', ...
    'fcnPrep',    fcnPrep, ...
    'fcnDraw',    fcnDraw, ...
    'parameters', {[settingNames, {'Time', 'PauseTime', 'PreStimTime', 'PostStimTime'}]}, ...
    'data',       [settingDefaults; timingData], ...
    'settings',   settings, ...
    'impulse',    false);