function layerData = imgTargetData()
    % Handles to the functions in this folder
    fcnPrep = @imgTargetPrep;
    fcnDraw = @imgTargetDraw;

    settingNames = {'Height', 'Width', 'Xpos', 'Ypos',...
                    'Velocity', 'Direction', 'Contrast'};
    % Data corresponds to the above setting names
    settingDefaults = [ 0; 0; 20; 20; 60; 0; 1];
    % Defaults for timing
    timingData = [60; 0; 0; 0];
    % Needed for layer settings manager to work
    settings.global = 1;
    settings.path  = {'Image Path', 'Images/circle_black.png', '*.*'};
    

    layerData = struct(...
    'name',       'Image Target', ...
    'fcnPrep',    fcnPrep, ...
    'fcnDraw',    fcnDraw, ...
    'parameters', {[settingNames, {'Time', 'PauseTime', 'PreStimTime', 'PostStimTime'}]}, ...
    'data',       [settingDefaults; timingData], ...
    'settings',   settings, ...
    'impulse',    false);