function layerData = whiteNoiseData()
    % Handles to the functions in this folder
    fcnPrep = @whiteNoisePrep;
    fcnDraw = @whiteNoiseDraw;

    settingNames = {'Height', 'Width', 'Xpos', 'Ypos',...
                    'Contrast', 'Pixels'};
    % Data corresponds to the above setting names
    settingDefaults = [80; 100; 320; 240; 1; 1];
    % Defaults for timing
    timingData = [60; 0; 0; 0];
    % Needed for layer settings manager to work
    settings.global = 1;
    settings.box{1}  = {'Offset X function', 0};
    settings.box{2}  = {'Offset Y function', 0};
    settings.edit{1} = {'X function: ', '100*sin(2*pi/3 *(n-1)*ifi)'};
    settings.edit{2} = {'Y function: ', '100*cos(2*pi/3 *(n-1)*ifi)'};

    layerData = struct(...
    'name',       "White Noise", ...
    'fcnPrep',    fcnPrep, ...
    'fcnDraw',    fcnDraw, ...
    'parameters', {[settingNames, {'Time', 'PauseTime', 'PreStimTime', 'PostStimTime'}]}, ...
    'data',       [settingDefaults; timingData], ...
    'settings',   settings, ...
    'impulse',    false);