function layerData = starfieldData()
    % Handles to the functions in this folder
    fcnPrep = @starfieldPrep;
    fcnDraw = @starfieldDraw;

    settingNames = {'Dot size', 'Dot density', ...
                    'Sideslip',  'Lift', 'Thrust', 'Pitch', 'Yaw', 'Roll', ...
                    'Background Noise', 'Retain into next Trial'};
    % Data corresponds to the above setting names
    settingDefaults = [2; 1; 0; 0; 0; 0; 0; 0; 0; 0];
    % Defaults for timing
    timingData = [60; 0; 0; 0];
    % Needed for layer settings manager to work
    settings.global = 1;

    

    layerData = struct(...
    'name',       "Starfield 2: 3D Space", ...
    'fcnPrep',    fcnPrep, ...
    'fcnDraw',    fcnDraw, ...
    'parameters', {[settingNames, {'Time', 'PauseTime', 'PreStimTime', 'PostStimTime'}]}, ...
    'data',       [settingDefaults; timingData], ...
    'settings',   settings, ...
    'impulse',    false);