function layerData = sineBackgroundTrueData()
    % Handles to the functions in this folder
    fcnPrep = @sineBackgroundTruePrep;
    fcnDraw = @sineBackgroundTrueDraw;

    settingNames = {'Wavelength', 'Temporal Freq', 'PatchHeight', ...
                    'patchWidth', 'Patch Xpos', 'Patch Ypos', 'Contrast'};
    
    % Data corresponds to the above setting names
    settingDefaults = [ 20; 2; 200; 200; 100; 100; 1];
    % Defaults for timing
    timingData = [60; 0; 0; 0];
    % Needed for layer settings manager to work
    settings.global = 1;

    layerData = struct(...
    'name',       'Sine Background True', ...
    'fcnPrep',    fcnPrep, ...
    'fcnDraw',    fcnDraw, ...
    'parameters', {[settingNames, {'Time', 'PauseTime', 'PreStimTime', 'PostStimTime'}]}, ...
    'data',       [settingDefaults; timingData], ...
    'settings',   settings, ...
    'impulse',    false);