function layerData = sineBackgroundData()
    % Handles to the functions in this folder
    fcnPrep = @sineBackgroundPrep;
    fcnDraw = @sineBackgroundDraw;

    settingNames = {'Wavelength', 'Temporal Freq', 'Contrast'}; 
    % Data corresponds to the above setting names
    settingDefaults = [20; 2; 1];
    % Defaults for timing
    timingData = [60; 0; 0; 0];
    % Needed for layer settings manager to work
    settings.global = 1;

    

    layerData = struct(...
    'name',       'Sine Background', ...
    'fcnPrep',    fcnPrep, ...
    'fcnDraw',    fcnDraw, ...
    'parameters', {[settingNames, {'Time', 'PauseTime', 'PreStimTime', 'PostStimTime'}]}, ...
    'data',       [settingDefaults; timingData], ...
    'settings',   settings, ...
    'impulse',    false);