function layerData = squareGratingData()
    % Handles to the functions in this folder
    fcnPrep = @squareGratingPrep;
    fcnDraw = @squareGratingDraw;

    settingNames = {'Wavelength', 'Temporal Freq', 'Direction', ...
                    'PatchHeight', 'patchWidth', 'Patch Xpos', 'Patch Ypos',...
                    'Contrast'}; 
    % Data corresponds to the above setting names
    settingDefaults = [ 20; 2; 0; 200; 200; 100; 100; 1];
    % Defaults for timing
    timingData = [60; 0; 0; 0];
    % Needed for layer settings manager to work
    settings.global = 1;

    

    layerData = struct(...
    'name',       'Square Grating', ...
    'fcnPrep',    fcnPrep, ...
    'fcnDraw',    fcnDraw, ...
    'parameters', {[settingNames, {'Time', 'PauseTime', 'PreStimTime', 'PostStimTime'}]}, ...
    'data',       [settingDefaults; timingData], ...
    'settings',   settings, ...
    'impulse',    false);