function layerData = DualAperturesData()
    % Handles to the functions in this folder
    fcnPrep = @DualAperturesPrep;
    fcnDraw = @DualAperturesDraw;

    settingNames = {'Opacity Surround', 'Brightness Surround', 'Opacity Hole', ...
                    'Brightness Hole', 'Width', 'Height', 'Xpos', 'Ypos' ...
                    'Width2', 'Height2', 'Xpos2', 'Ypos2'};
    % Data corresponds to the above setting names
    settingDefaults = [255; 127; 0; 255; 100; 100; 320; 280; 50; 50; 100; 100];
    % Defaults for timing
    timingData = [60; 0; 0; 0];
    % Needed for layer settings manager to work
    settings.global   = 1;
    settings.box{1} = {'Use Rect for 1', 0};
    settings.box{2} = {'Use Rect for 2', 0};

    layerData = struct(...
    'name',       'Dual Apertures', ...
    'fcnPrep',    fcnPrep, ...
    'fcnDraw',    fcnDraw, ...
    'parameters', {[settingNames, {'Time', 'PauseTime', 'PreStimTime', 'PostStimTime'}]}, ...
    'data',       [settingDefaults; timingData], ...
    'settings',   settings, ...
    'impulse',    false);