function layerData = target3dData()
    % Handles to the functions in this folder
    fcnPrep = @target3dPrep; 
    fcnDraw = @target3dDraw; 

    settingNames = {'Target Size', 'Target Start Azimuth', 'Target Start Elevation', 'Target Start Distance', ...
                    'Target End Azimuth', 'Target End Elevation', 'Target End Distance', ...
                    'Velocity', 'Target Noise'};
    % Data corresponds to the above setting names
    settingDefaults = [1; 0; 0; 50; 0; 0; 20; 10; 0];
    % Defaults for timing
    timingData = [60; 0; 0; 0];
    % Needed for layer settings manager to work
    settings.global = 0;
    settings.pursuit = false;
    

    layerData = struct(...
    'name',       '3D Target', ...
    'fcnPrep',    fcnPrep, ...
    'fcnDraw',    fcnDraw, ...
    'parameters', {[settingNames, {'Time', 'PauseTime', 'PreStimTime', 'PostStimTime'}]}, ...
    'data',       [settingDefaults; timingData], ...
    'settings',   settings, ...
    'impulse',    false);