function layerData = target3dGeneralData()
    % Handles to the functions in this folder
    fcnPrep = @target3dGeneralPrep;
    fcnDraw = @target3dGeneralDraw;

    settingNames = {'Target Size', ...
                    'X Start', 'Y Start', 'Z Start', 'X End', 'Y End', 'Z End'};
    % Data corresponds to the above setting names
    settingDefaults = [2; 0; 0; 0; 0; 0; 0];
    % Defaults for timing
    timingData = [60; 0; 0; 0];
    % Needed for layer settings manager to work
    settings.global = 1;

    layerData = struct(...
    'name',       "Targed 3D General", ...
    'fcnPrep',    fcnPrep, ...
    'fcnDraw',    fcnDraw, ...
    'parameters', {[settingNames, {'Time', 'PauseTime', 'PreStimTime', 'PostStimTime'}]}, ...
    'data',       [settingDefaults; timingData], ...
    'settings',   settings, ...
    'impulse',    false);