function layerData = mouseTargetData()
    % Handles to the functions in this folder
    fcnPrep = @mouseTargetPrep;
    fcnDraw = @mouseTargetDraw;

    settingNames = {'Width', 'Height', 'Brightness'};
    % Data corresponds to the above setting names
    settingDefaults = [5; 100; 0];
    % Defaults for timing
    timingData = [60; 0; 0; 0];
    % Needed for layer settings manager to work
    settings.global = 1;

    layerData = struct(...
    'name',       'Mouse Target', ...
    'fcnPrep',    fcnPrep, ...
    'fcnDraw',    fcnDraw, ...
    'parameters', {[settingNames, {'Time', 'PauseTime', 'PreStimTime', 'PostStimTime'}]}, ...
    'data',       [settingDefaults; timingData], ...
    'settings',   settings, ...
    'impulse',    false);