function layerData = imgTargetFlickerData()
    % Handles to the functions in this folder
    fcnPrep = @imgTargetFlickerPrep;
    fcnDraw = @imgTargetFlickerDraw;

    settingNames = {'Height', 'Width', 'Xpos', 'Ypos',...
                    'Velocity', 'Direction', 'Contrast1', ...
                    'Contrast2', 'FlickerFramesPerCycle'};
    % Data corresponds to the above setting names
    settingDefaults = [0; 0; 20; 20; 60; 0; 1; -1; 0];
    % Defaults for timing
    timingData = [60; 0; 0; 0];
    % Needed for layer settings manager to work
    settings.global = 1;
    settings.path   = {'Image Path', 'Images/circle_black.png', '*.*'};

    layerData = struct(...
    'name',       "Image Target Flicker", ...
    'fcnPrep',    fcnPrep, ...
    'fcnDraw',    fcnDraw, ...
    'parameters', {[settingNames, {'Time', 'PauseTime', 'PreStimTime', 'PostStimTime'}]}, ...
    'data',       [settingDefaults; timingData], ...
    'settings',   settings, ...
    'impulse',    false);