function layerData = target3dXYZData()
    % Handles to the functions in this folder
    fcnPrep = @target3dXYZPrep;
    fcnDraw = @target3dXYZDraw;

    settingNames = {'Size', 'X', 'Y', 'Z'};
    % Data corresponds to the above setting names
    settingDefaults = [ 0.8; 0; 0; 0];
    % Defaults for timing
    timingData = [60; 0; 0; 0];
    % Needed for layer settings manager to work
    settings.global = 1;

    layerData = struct(...
    'name',       "Target 3D XYZ", ...
    'fcnPrep',    fcnPrep, ...
    'fcnDraw',    fcnDraw, ...
    'parameters', {[settingNames, {'Time', 'PauseTime', 'PreStimTime', 'PostStimTime'}]}, ...
    'data',       [settingDefaults; timingData], ...
    'settings',   settings, ...
    'impulse',    false);