function layerData = sineWaveBackgroundData()
    % Handles to the functions in this folder
    fcnPrep = @sineWaveBackgroundPrep;
    fcnDraw = @sineWaveBackgroundDraw;

    settingNames = {'Temporal Freq', 'Contrast', 'PatchHeight', ...
                    'patchWidth', 'Patch Xpos', 'Patch Ypos'}; 
    % Data corresponds to the above setting names
    settingDefaults = [2; 1; 200; 200; 100; 100;];
    % Defaults for timing
    timingData = [60; 0; 0; 0];
    % Needed for layer settings manager to work
    settings.global = 1;

    

    layerData = struct(...
    'name',       'Sine Wave Background', ...
    'fcnPrep',    fcnPrep, ...
    'fcnDraw',    fcnDraw, ...
    'parameters', {[settingNames, {'Time', 'PauseTime', 'PreStimTime', 'PostStimTime'}]}, ...
    'data',       [settingDefaults; timingData], ...
    'settings',   settings, ...
    'impulse',    false);