function layerData = prTargetData()
    % Handles to the functions in this folder
    fcnPrep = @prTargetPrep;
    fcnDraw = @prTargetDraw;

    settingNames = {'Window Width', 'Window Height', 'Window X', 'Window Y', ...
                    'X Start', 'Y Start', 'X End', 'Y End', ...
                    'Speed in pixels per s', ...
                    'Motion Time'};
    % Data corresponds to the above setting names
    settingDefaults = [720; 720; 1280; 1080; 0; 0; 0; 0; 900; 17];
    % Defaults for timing
    timingData = [41; 20; 20; 20];
    % Needed for layer settings manager to work
    settings.global = 1;

    layerData = struct(...
    'name',       'Paloma Target Replication', ...
    'fcnPrep',    fcnPrep, ...
    'fcnDraw',    fcnDraw, ...
    'parameters', {[settingNames, {'Time', 'PauseTime', 'PreStimTime', 'PostStimTime'}]}, ...
    'data',       [settingDefaults; timingData], ...
    'settings',   settings, ...
    'impulse',    false);
